// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Arch() {
  return window['go']['main']['App']['Arch']();
}

export function AutoTypeSupported() {
  return window['go']['main']['App']['AutoTypeSupported']();
}

export function CanDetectOsSleep() {
  return window['go']['main']['App']['CanDetectOsSleep']();
}

export function CancelRestart() {
  return window['go']['main']['App']['CancelRestart']();
}

export function CheckOpenFiles() {
  return window['go']['main']['App']['CheckOpenFiles']();
}

export function ClearClipboardText() {
  return window['go']['main']['App']['ClearClipboardText']();
}

export function ClipboardSupported() {
  return window['go']['main']['App']['ClipboardSupported']();
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DevTools() {
  return window['go']['main']['App']['DevTools']();
}

export function Exit() {
  return window['go']['main']['App']['Exit']();
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetAppPath(arg1) {
  return window['go']['main']['App']['GetAppPath'](arg1);
}

export function GetClipboardText() {
  return window['go']['main']['App']['GetClipboardText']();
}

export function GetDocumentsPath(arg1) {
  return window['go']['main']['App']['GetDocumentsPath'](arg1);
}

export function GetSaveFileName(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetSaveFileName'](arg1, arg2, arg3, arg4);
}

export function GetTempPath(arg1) {
  return window['go']['main']['App']['GetTempPath'](arg1);
}

export function GetUserDataPath(arg1) {
  return window['go']['main']['App']['GetUserDataPath'](arg1);
}

export function GetWorkDirPath(arg1) {
  return window['go']['main']['App']['GetWorkDirPath'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideApp() {
  return window['go']['main']['App']['HideApp']();
}

export function IsAppFocused() {
  return window['go']['main']['App']['IsAppFocused']();
}

export function JoinPath(arg1) {
  return window['go']['main']['App']['JoinPath'](arg1);
}

export function LoadConfig(arg1) {
  return window['go']['main']['App']['LoadConfig'](arg1);
}

export function MainWindowMaximized() {
  return window['go']['main']['App']['MainWindowMaximized']();
}

export function MaximizeMainWindow() {
  return window['go']['main']['App']['MaximizeMainWindow']();
}

export function MinimizeApp(arg1, arg2) {
  return window['go']['main']['App']['MinimizeApp'](arg1, arg2);
}

export function MinimizeMainWindow() {
  return window['go']['main']['App']['MinimizeMainWindow']();
}

export function Mkdir(arg1) {
  return window['go']['main']['App']['Mkdir'](arg1);
}

export function Name() {
  return window['go']['main']['App']['Name']();
}

export function OpenDevTools() {
  return window['go']['main']['App']['OpenDevTools']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenLink(arg1) {
  return window['go']['main']['App']['OpenLink'](arg1);
}

export function ParsePath(arg1) {
  return window['go']['main']['App']['ParsePath'](arg1);
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RequestExit() {
  return window['go']['main']['App']['RequestExit']();
}

export function RequestRestartAndUpdate(arg1) {
  return window['go']['main']['App']['RequestRestartAndUpdate'](arg1);
}

export function ResolveProxy(arg1) {
  return window['go']['main']['App']['ResolveProxy'](arg1);
}

export function RestoreMainWindow() {
  return window['go']['main']['App']['RestoreMainWindow']();
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SetClipboardText(arg1) {
  return window['go']['main']['App']['SetClipboardText'](arg1);
}

export function SetGlobalShortcuts(arg1) {
  return window['go']['main']['App']['SetGlobalShortcuts'](arg1);
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}

export function Spawn(arg1) {
  return window['go']['main']['App']['Spawn'](arg1);
}

export function StatFile(arg1) {
  return window['go']['main']['App']['StatFile'](arg1);
}

export function ThirdPartyStoragesSupported() {
  return window['go']['main']['App']['ThirdPartyStoragesSupported']();
}

export function UpdaterEnabled() {
  return window['go']['main']['App']['UpdaterEnabled']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
