// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {fs} from '../models';

export function Arch():Promise<string>;

export function AutoTypeSupported():Promise<boolean>;

export function CanDetectOsSleep():Promise<boolean>;

export function CancelRestart():Promise<void>;

export function CheckOpenFiles():Promise<void>;

export function ClearClipboardText():Promise<void>;

export function ClipboardSupported():Promise<boolean>;

export function CloseDatabase():Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DevTools():Promise<boolean>;

export function Exit():Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetAppPath(arg1:string):Promise<string>;

export function GetClipboardText():Promise<string>;

export function GetDatabaseName():Promise<string>;

export function GetDocumentsPath(arg1:string):Promise<string>;

export function GetEntries():Promise<Array<main.KDBXEntry>>;

export function GetGroups():Promise<Array<main.KDBXGroup>>;

export function GetOpenFileName(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function GetSaveFileName(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetTempPath(arg1:string):Promise<string>;

export function GetUserDataPath(arg1:string):Promise<string>;

export function GetWorkDirPath(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function HideApp():Promise<void>;

export function IsAppFocused():Promise<boolean>;

export function IsDatabaseOpen():Promise<boolean>;

export function JoinPath(arg1:Array<string>):Promise<string>;

export function LoadConfig(arg1:string):Promise<string>;

export function MainWindowMaximized():Promise<boolean>;

export function MaximizeMainWindow():Promise<void>;

export function MinimizeApp(arg1:string,arg2:string):Promise<void>;

export function MinimizeMainWindow():Promise<void>;

export function Mkdir(arg1:string):Promise<void>;

export function Name():Promise<string>;

export function OpenDatabase(arg1:string,arg2:string):Promise<Record<string, any>>;

export function OpenDevTools():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenLink(arg1:string):Promise<void>;

export function ParsePath(arg1:string):Promise<Record<string, string>>;

export function Platform():Promise<string>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function RequestExit():Promise<void>;

export function RequestRestartAndUpdate(arg1:string):Promise<void>;

export function ResolveProxy(arg1:string):Promise<Record<string, any>>;

export function RestoreMainWindow():Promise<void>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;

export function SetClipboardText(arg1:string):Promise<void>;

export function SetGlobalShortcuts(arg1:Record<string, any>):Promise<void>;

export function ShowMainWindow():Promise<void>;

export function Spawn(arg1:Record<string, any>):Promise<Record<string, any>>;

export function StatFile(arg1:string):Promise<fs.FileInfo>;

export function ThirdPartyStoragesSupported():Promise<boolean>;

export function UpdaterEnabled():Promise<boolean>;

export function Version():Promise<string>;

export function WriteFile(arg1:string,arg2:Array<number>):Promise<void>;
